shard.0.host=localhost
shard.0.port=5432
shard.0.name=route0
shard.0.user=postgres
shard.0.password=1234567890

shard.1.host=localhost
shard.1.port=5433
shard.1.name=route1
shard.1.user=postgres
shard.1.password=1234567890

shard.2.host=localhost
shard.2.port=5434
shard.2.name=route2
shard.2.user=postgres
shard.2.password=1234567890