shard.0.host=***
shard.0.port=***
shard.0.name=***
shard.0.user=***
shard.0.password=***

shard.1.host=***
shard.1.port=***
shard.1.name=***
shard.1.user=***
shard.1.password=***

shard.2.host=***
shard.2.port=***
shard.2.name=***
shard.2.user=***
shard.2.password=***